prepublish hook - make sensitive to files in entire directory

diff --git a/npm-hooks/prepublish b/npm-hooks/prepublish
--- a/npm-hooks/prepublish
+++ b/npm-hooks/prepublish
@@ -11,6 +11,14 @@ cd `dirname "$0"`/..
 yellow='\e[33m'
 normal='\e[0m'
 
+git ls-files --error-unmatch `find . -type f | egrep -v '^\./(node_modules|\.git)'` >/dev/null
+if [ "$?" != "0" ]; then
+  echo
+  echo -e "${yellow}pre-publish: abort due to files in package which aren't in repo${normal}" >/dev/stderr
+  echo
+  exit 1
+fi
+
 (git status --porcelain; echo DONE DONE) \
 | while read status filename
   do
@@ -29,14 +37,6 @@ normal='\e[0m'
 if [ "$?" != "0" ]; then
   echo
   echo -e "${yellow}pre-publish: abort due to modified files${normal}" >/dev/stderr
-  echo
-  exit 1
-fi
-
-git ls-files --error-unmatch `find src -type f; find tests -type f` >/dev/null
-if [ "$?" != "0" ]; then
-  echo
-  echo -e "${yellow}pre-publish: abort due to files in package which aren't in repo${normal}" >/dev/stderr
   echo
   exit 1
 fi
